### ISSUE TITLE
Console publisher doesn't work in VSCode

### ISSUE THREAD

**Issue by OsvaldoRosado** [Microsoft/node-diagnostic-channel#22]
VSCode has a non-standard console object, that the diagnostic channel publisher clobbers.

Patching individual methods rather than the whole object may be a solution here.

**Comment by eamodio** [comment]
FYI, this is related to https://github.com/Microsoft/vscode/issues/26641

**Comment by OsvaldoRosado** [comment]
Addressed in #23
