### ISSUE TITLE
Support for Massivejs / Pg-promise

### ISSUE THREAD

**Issue by gpierrick** [Microsoft/node-diagnostic-channel#42]
Hi I am not sure if it's the right repo to post this in but I am using https://github.com/dmfay/massive-js
which internally uses pg-promise not pg with Application Insights and I am not seeing any sql trace in the Azure portal.

Any ideas on how I could make this work?

Thanks

**Comment by SergeyKanzhelev** [comment]
can we take a step back. Are you saying you are using Application Insights to monitor your application and it doesn't collect SQL calls made via massive-js?

If so - the best repository to ask would be https://github.com/microsoft/applicationinsights-node.js.

CC: @OsvaldoRosado

**Comment by gpierrick** [comment]
Hi Sergey that's correct. App insights doesn't seem to be tracking SQL calls with massivejs

**Comment by SergeyKanzhelev** [comment]
@OsvaldoRosado can you please help here?

**Comment by OsvaldoRosado** [comment]
This seems like the correct repo to me for fixing the lack of collection. This is either a bug in the pg publisher from diagnostic-channel-publishers or a feature request for a new publisher if pg-promise doesn’t call pg internally. 

@MSLaguana @jackhorton Do you guys know if we should be sending events for pg-promise from the pg publisher?

@gpierrick Please do open a related issue on the repo linked above for the Application Insights SDK and we can guide you through workarounds without autocollection.

**Comment by gpierrick** [comment]
Thanks @OsvaldoRosado will do now - pg-promise does use pg internally

https://github.com/brianc/node-postgres (pg)

https://github.com/vitaly-t/pg-promise/blob/master/package.json (pg-promise)

**Comment by gpierrick** [comment]
https://github.com/Microsoft/ApplicationInsights-node.js/issues/376

**Comment by MSLaguana** [comment]
Looks like `pg-promise` uses `pg@7.4.1` (at least the tip of master does at the moment) while right now we have written support for `pg@6.x`. Someone will need to investigate whether `pg@7.x` has changed any of their internals to break our monkey patching, or if we can just apply the same patches to the new version.

**Comment by markwolff** [comment]
Closing this as pg v7 is now supported as of `0.3.0` of diagnostic-channel-publishers (from #51) and [`1.2.0` of application insights](https://github.com/Microsoft/ApplicationInsights-node.js/releases/tag/1.2.0)

I assume this means `pg-promise` will also work after upgrading
