### ISSUE TITLE
pg v7 support

### ISSUE THREAD

**Issue by csuich2** [Microsoft/node-diagnostic-channel#45]
Per https://github.com/Microsoft/node-diagnostic-channel/blob/master/src/diagnostic-channel-publishers/README.md, only pg v6 is supported by the diagnostic channel, which means we can't use pg v7. pg v6 is now over a year old. Is there any timeline for supporting newer versions of pg?

Although I don't use it, I suspect some folks may like to see pg-pool v2 supported as well since the update to pg-pool v1 was in June of 2017.

**Comment by csuich2** [comment]
https://github.com/Microsoft/ApplicationInsights-node.js/issues/415

**Comment by csuich2** [comment]
See https://github.com/Microsoft/ApplicationInsights-node.js/issues/415

**Comment by markwolff** [comment]
Closing this as pg v7 is now supported as of `0.3.0` of diagnostic-channel-publishers (from #51) and [`1.2.0` of application insights](https://github.com/Microsoft/ApplicationInsights-node.js/releases/tag/1.2.0)
