### ISSUE TITLE
Module not found: Can't resolve '@opentelemetry/tracing'

### ISSUE THREAD

**Issue by DivisionSi** [microsoft/node-diagnostic-channel#72]
My npm build has all of a sudden started to fail.

Error: ./node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js
  Module not found: Can't resolve '@opentelemetry/tracing' in 'e:\vsts\a\4899\s\node_modules\diagnostic-channel-publishers\dist\src'

Node: 12.16.3
npm: 6.12.1

**Comment by leosvelperez** [comment]
@DivisionSi did you solve the issue? I manually installed the `@opentelemetry/tracing` package but then I get:
```
WARNING in ./node_modules/@opentelemetry/core/build/src/platform/node/BasePlugin.js 74:46-103
Critical dependency: the request of a dependency is an expression
```

**Comment by markwolff** [comment]
> @DivisionSi did you solve this issue? I manually installed the `@opentelemetry/tracing` package but then I get:
> 
> ```
> WARNING in ./node_modules/@opentelemetry/core/build/src/platform/node/BasePlugin.js 74:46-103
> Critical dependency: the request of a dependency is an expression
> ```

Are you using webpack to bundle your app? Also are you using one of the azure SDKs? The tracing module should only be attempted to be imported when you are using an azure SDK package. It is also considered an "optional" dependency here, but I'm wondering if webpack is disregarding this somehow?
https://github.com/microsoft/node-diagnostic-channel/blob/3ed2bd173de99e7b9898e1faafee668a20787439/src/diagnostic-channel-publishers/src/azure-coretracing.pub.ts#L18-L19

**Comment by leosvelperez** [comment]
@markwolff yes, I'm using webpack and an Azure SDK. It's an Angular project with a Express.js server for server-side rendering. It doesn't fail my build, it's throwing warnings. I tried to get rid of the warnings by installing the `@opentelemetry/tracing` package, but the I start to get the other warning I mentioned above.

**Comment by vpetersen** [comment]
Did anyone come up with a resolution for this issue?

**Comment by tiavina-mika** [comment]
is there any fix on it?
